/**
 * Build-time prerender for the marketing routes.
 *
 * The app is a client-rendered Vite SPA: `dist/index.html` ships an empty
 * `<div id="root">` and all copy is painted by React after the JS loads. That
 * means Google (partially) and the AI answer crawlers that DON'T run JS
 * (GPTBot, ClaudeBot, PerplexityBot, Google-Extended) see a blank page on the
 * money pages. This step fixes that: it serves the freshly built `dist/`,
 * drives a headless Chromium to each marketing route, waits for React to paint,
 * forces every scroll-reveal section visible, and writes the fully-rendered
 * HTML back to `dist/<route>/index.html`.
 *
 * Vercel serves a matching static file before falling through to the SPA
 * catch-all rewrite (`/(.*) -> /index.html`), so crawlers get real HTML while
 * humans still get the live React app, which mounts on top of the prerendered
 * markup (createRoot re-renders identical content — no hydration contract).
 *
 * ── Zero-regression contract ─────────────────────────────────────────────
 * This script NEVER fails the build. If Chromium can't launch (e.g. on a CI
 * runner without the browser), it logs a warning and exits 0, leaving the
 * normal SPA `dist/` exactly as `vite build` produced it. Worst case is
 * today's behavior; best case is prerendered HTML. There is no downside.
 *
 * ── Guardrails ───────────────────────────────────────────────────────────
 * - Only the routes in ROUTES are touched. `/lp/*` pages are already static
 *   (generated by gen_lp.py) and are intentionally NOT in this list.
 * - Content is captured verbatim from what React renders — no titles, H1s,
 *   canonicals, or copy are rewritten here.
 */

import http from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.resolve(__dirname, '..', 'dist');
const PORT = 5177;

// Marketing / content routes worth prerendering. Deliberately excludes:
//   • /lp/*            — already static (gen_lp.py), do not touch
//   • /r/*, /admin/*   — private/dynamic dashboards, non-indexable
//   • /audit, /swarm, /lead-gen — interactive tools, no crawlable copy
const ROUTES = [
  '/',
  '/pricing',
  '/retainer',
  '/work',
  '/managed',
  '/diy',
  '/methodology',
  '/case-studies',
  '/case-studies/sandbar',
  '/vs',
  '/vs/localiq',
  '/vs/brightlocal',
  '/vs/scorpion',
  '/vs/podium',
  '/apply',
  '/growth-score',
];

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
};

/** Minimal static server over dist/ with SPA fallback to index.html. */
function startServer() {
  const server = http.createServer(async (req, res) => {
    try {
      const urlPath = decodeURIComponent((req.url || '/').split('?')[0]);
      let filePath = path.join(DIST, urlPath);
      const ext = path.extname(urlPath);
      // No extension → a client route → serve the SPA shell so React can boot.
      if (!ext || !existsSync(filePath)) {
        if (ext && existsSync(filePath)) {
          // fall through
        } else if (!ext) {
          filePath = path.join(DIST, 'index.html');
        }
      }
      if (!existsSync(filePath)) {
        res.statusCode = 404;
        res.end('not found');
        return;
      }
      const body = await readFile(filePath);
      res.setHeader('Content-Type', MIME[path.extname(filePath)] || 'application/octet-stream');
      res.end(body);
    } catch (err) {
      res.statusCode = 500;
      res.end(String(err));
    }
  });
  return new Promise((resolve) => server.listen(PORT, () => resolve(server)));
}

/**
 * Locate a usable Chromium executable without hitting the network. Some
 * environments (this one, and locked-down CI) pre-install the browser under
 * PLAYWRIGHT_BROWSERS_PATH but pin a different bundled version than the
 * `playwright` package expects, so `launch()` would try to re-download and
 * fail. Prefer an on-disk binary; env override wins.
 */
function findChromiumExecutable() {
  const candidates = [];
  if (process.env.PRERENDER_CHROMIUM) candidates.push(process.env.PRERENDER_CHROMIUM);
  const root = process.env.PLAYWRIGHT_BROWSERS_PATH;
  if (root) {
    candidates.push(path.join(root, 'chromium')); // symlink some images ship
    // Any chromium-*/chrome-linux/chrome under the browsers root.
    try {
      for (const dir of ['chromium', 'chromium-*']) void dir;
    } catch { /* ignore */ }
  }
  candidates.push('/opt/pw-browsers/chromium');
  for (const c of candidates) {
    try { if (c && existsSync(c)) return c; } catch { /* ignore */ }
  }
  return null;
}

/** Load Playwright's chromium, installing the browser once if it's missing. */
async function getChromium() {
  const { chromium } = await import('playwright');
  const executablePath = findChromiumExecutable();
  const launchOpts = { args: ['--no-sandbox'] };
  if (executablePath) launchOpts.executablePath = executablePath;
  try {
    return await chromium.launch(launchOpts);
  } catch (err) {
    // No usable binary — try a one-time install (works where the CDN is allowed).
    console.warn('[prerender] chromium launch failed, attempting install…', err?.message);
    try {
      execSync('npx --yes playwright install chromium', { stdio: 'inherit' });
      return await chromium.launch({ args: ['--no-sandbox'] });
    } catch (err2) {
      throw new Error(`chromium unavailable: ${err2?.message || err2}`);
    }
  }
}

async function outPathFor(route) {
  if (route === '/') return path.join(DIST, 'index.html');
  const dir = path.join(DIST, route.replace(/^\//, ''));
  await mkdir(dir, { recursive: true });
  return path.join(dir, 'index.html');
}

async function main() {
  if (!existsSync(path.join(DIST, 'index.html'))) {
    console.warn('[prerender] dist/index.html missing — did vite build run? Skipping.');
    return;
  }

  let server;
  let browser;
  try {
    server = await startServer();
    browser = await getChromium();
  } catch (err) {
    console.warn(`[prerender] skipped (no browser): ${err?.message || err}`);
    if (server) server.close();
    return; // ← zero-regression: leave the SPA dist untouched
  }

  const base = `http://127.0.0.1:${PORT}`;
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 1600 } });
  let ok = 0;
  let failed = 0;

  for (const route of ROUTES) {
    const page = await ctx.newPage();
    try {
      await page.goto(base + route, { waitUntil: 'networkidle', timeout: 20000 });
      // Wait for the lazy route chunk to mount real content.
      await page.waitForFunction(
        () => {
          const root = document.getElementById('root');
          return !!root && (root.innerText || '').trim().length > 300;
        },
        { timeout: 20000 }
      );
      // Force every scroll-reveal section visible so all copy is in the static
      // HTML (IntersectionObserver never fires below the fold in headless).
      await page.evaluate(() => {
        document.querySelectorAll('.reveal').forEach((el) => el.classList.add('reveal-in'));
      });
      await page.waitForTimeout(250); // let count-up / typewriter settle a beat
      const html = '<!DOCTYPE html>\n' + (await page.content()).replace(/^<!DOCTYPE html>/i, '').trimStart();
      const out = await outPathFor(route);
      await writeFile(out, html, 'utf8');
      const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
      console.log(`[prerender] ✓ ${route.padEnd(26)} → ${path.relative(DIST, out)} (${kb} KB)`);
      ok++;
    } catch (err) {
      console.warn(`[prerender] ✗ ${route} — ${err?.message || err} (left as SPA fallback)`);
      failed++;
    } finally {
      await page.close();
    }
  }

  await ctx.close();
  await browser.close();
  server.close();
  console.log(`[prerender] done — ${ok} prerendered, ${failed} skipped.`);
}

main().catch((err) => {
  // Absolute backstop: prerender must never break the build.
  console.warn('[prerender] fatal (ignored, SPA build intact):', err?.message || err);
  process.exit(0);
});
